// Action types for Blue Green functionality.
export const BLUEGREEN_EC2_CALL_FAILED = 'BLUEEGREEN_EC2_CALL_FAILED';
export const BLUEGREEN_FETCH_INSTANCES = 'BLUEGREEN_FETCH_INSTANCES';
export const BLUEGREEN_DEPLOY_INSTANCE = 'BLUEGREEN_DEPLOY_INSTANCE';
export const BLUEGREEN_UPDATE_DEPLOYED = 'BLUEGREEN_UPDATE_DEPLOYED';
export const BLUEGREEN_UPDATE_INSTANCES = 'BLUEGREEN_UPDATE_INSTANCES';
export const BLUEGREEN_DEREGISTER = 'BLUEGREEN_DEREGISTER';
