// Action types for Blue Green functionality.
export const BLUEGREEN_EC2_CALL_FAILED = 'BLUEEGREEN_EC2_CALL_FAILED';

export const BLUEGREEN_FETCH_INSTANCES = 'BLUEGREEN_FETCH_INSTANCES';
export const BLUEGREEN_UPDATE_INSTANCES = 'BLUEGREEN_UPDATE_INSTANCES';

export const BLUEGREEN_DEREGISTER = 'BLUEGREEN_DEREGISTER';

export const BLUEGREEN_FETCH_DEPLOYED = 'BLUEGREEN_FETCH_DEPLOYED';
export const BLUEGREEN_DEPLOY_INSTANCE = 'BLUEGREEN_DEPLOY_INSTANCE';
export const BLUEGREEN_INSTANCE_DEPLOYED = 'BLUEGREEN_INSTANCE_DEPLOYED';

// AMISelect events.
export const AMISELECT_EC2_CALL_FAILED = 'BLUEEGREEN_EC2_CALL_FAILED';

export const AMISELECT_FETCH_AMIS = 'AMISELECT_FETCH_INSTANCES';
export const AMISELECT_AMIS_FETCHED = 'AMISELECT_AMIS_FETCHED';

// InstanceSelect events.
export const INSTANCESELECT_EC2_CALL_FAILED =
  'INSTANCESELECT_EC2_CALL_FAILED';

export const INSTANCESELECT_FETCH_INSTANCES =
  'INSTANCESELECT_FETCH_INSTANCES';

export const INSTANCESELECT_INSTANCES_FETCHED =
  'INSTANCESELECT_INSTANCES_FETCHED';

// MessageBox events.
export const MESSAGE_CLEAR = 'MESSAGE_CLEAR';
export const MESSAGE_SET = 'MESSAGE_SET';

